import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSidebar  from "@/components/AppSidebar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import CoreProvider from "@/components/core-provider";
import NavBar from "@/components/NavBar";
import ClickSpark from "@/blocks/Animations/ClickSpark/ClickSpark";
import AuthWrapper from "@/components/AuthWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShadCN Tutorial",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundImage: 'radial-gradient(circle at 1px 1px, rgba(255,255,255,0.15) 1px, transparent 0), radial-gradient(circle at 2px 2px, rgba(255,255,255,0.08) 1px, transparent 0)',
          backgroundSize: '20px 20px, 40px 40px'
        }}
        suppressHydrationWarning={true}
      > 
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClickSpark
            sparkColor='#fff'
            sparkSize={10}
            sparkRadius={15}
            sparkCount={8}
            duration={400}
          >
          <CoreProvider>
            <AuthWrapper>
              <SidebarProvider defaultOpen={defaultOpen}>
                <AppSidebar/>
                <main className="min-h-screen w-full max-w-full overflow-x-hidden pt-18 lg:pt-0">
                  <NavBar/>
                  <div className="w-full max-w-full px-2 sm:px-4 lg:px-6">
                    {children}
                  </div>
                </main>
              </SidebarProvider>
            </AuthWrapper>
          </CoreProvider>
          </ClickSpark>
        </ThemeProvider>
      </body>
    </html>
  );
}
